### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by az84**

### CODE REVIEW

**Review by dearg-amadaun — APPROVED** [review]
Looks good.

**Review by dearg-amadaun — APPROVED** [review]

**Review by dearg-amadaun — APPROVED** [review]

**Review by dearg-amadaun — APPROVED** [review]

**Review by dearg-amadaun — APPROVED** [review]
Did I do it right? Will they merge now?

**Comment by az84** [comment]
It still shows it is open.

**Comment by dearg-amadaun** [comment]
Can I merge them now?

**Review by dearg-amadaun — APPROVED** [review]
Approved?

**Review by DSpenn — APPROVED** [review]

**Pull request merged**
